<?php

namespace AppBundle\Repository;

/**
 * DeclarateApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclarateApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
