<?php

namespace AppBundle\Repository;

/**
 * LevelApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
