<?php

namespace AppBundle\Repository;

/**
 * RechargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechargeRepository extends \Doctrine\ORM\EntityRepository
{
}
