<?php

namespace AppBundle\Repository;

/**
 * UserWalletHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWalletHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
