# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        AppBundle\Entity\Admin:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_SUPER:  ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        provider_users:
            entity:
                class: AppBundle\Entity\User
                property: username
        provider_admins:
            entity:
                class: AppBundle\Entity\Admin
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|output)/
            security: false

        user:
            pattern: ^/user
            provider: provider_users
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_homepage
                failure_path: user_login
            logout:
                invalidate_session: true
                path: /user/logout
                target: user_login

        admin:
            pattern: ^/admin
            provider: provider_admins
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: admin_homepage
                failure_path: admin_login
            logout:
                invalidate_session: true
                path: /admin/logout
                target: admin_login

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
