# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ['@security.encoder_factory', '@doctrine.orm.entity_manager', AppBundle\Entity\User]

    app.admin_manager:
        class: AppBundle\Manager\UserManager
        arguments: ['@security.encoder_factory', '@doctrine.orm.entity_manager', AppBundle\Entity\Admin]

    app.common_manager:
        class: AppBundle\Manager\CommonManager
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    app.transaction_manager:
        class: AppBundle\Manager\TransactionManager
        arguments: ['@doctrine.orm.entity_manager', AppBundle\Entity\Transaction]
