# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    user.class: AppBundle\Entity\User
    guest.class: AppBundle\Entity\Guest

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    user_manager:
        class: AppBundle\Manager\UserManager
        arguments: [@security.encoder_factory, @doctrine.orm.entity_manager, "%user.class%"]

    guest_manager:
        class: AppBundle\Manager\GuestManager
        arguments: [@security.encoder_factory, @doctrine.orm.entity_manager, "%user.class%"]

    book_manager:
        class: AppBundle\Manager\BookManager
        arguments: ["%kernel.root_dir%", @doctrine.orm.entity_manager, @security.context]

    cart_manager:
        class: AppBundle\Manager\CartManager
        arguments: [@session]

    book_order_manager:
        class: AppBundle\Manager\BookOrderManager
        arguments: [@doctrine.orm.entity_manager, @security.context, @session]